### PR TITLE
Add editor snippets

### PR DESCRIPTION
**Pull request by yuridev24**
Like a CCS playground.
- You can create snippets and use editor as before
- (NEW) You can click 'save' button to make your snippet in a sharable link to share your script or re-open it later!
- Anyone with the link can view the script but not modify it/delete it (if they edit, they won't be saved but if they click Save button, a new snippet or link will be generated).

For this to work, I dmed @thetrouper to add these environment variables to Vercel first. (if you add them after merging PR, trigger a new commit/deployment so it show up on website).

try before you merge: https://clickcrystals.vercel.app/editor/WWgfFawUcQ (you will see my snippet but yeah whatever u write there lmao)

### CODE REVIEW

**Comment by yuridev24** [comment]
And some little changes aswell. Your preview probably won't work till you don't add environment variables

**Comment by ItziSpyder** [comment]
Great pull request, I'll just wait for @thetrouper to edit the environmental variables first.

**Comment by thetrouper** [comment]
I hope you realize that these pull requests are all public, you just shared the database key to everyone. Please change it and DM it to me on discord.

**Comment by yuridev24** [comment]
Ok wait.

**Comment by yuridev24** [comment]
I dmed @thetrouper with the new URL and Key.

**Comment by ItziSpyder** [comment]
> I dmed @thetrouper with the new URL and Key.

can you also dm me the new URL and key

**Comment by devashish2024** [comment]
bump
@thetrouper @ItziSpyder

**Comment by I-No-oNe** [comment]
What is going on with this pr?

**Pull request merged**
